[tool.poetry]
name = "python-data-analysis-notebooks"
version = "0.1.0"
description = ""
authors = ["Simon Kirby <s.kirby@exeter.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
